from typing import Protocol


class PaymentProvider(Protocol):
    async def checkout(self, payment, booking) -> dict: ...
    async def retrieve(self, payment) -> dict | None: ...
    async def refund(self, payment, operation) -> dict: ...
    async def transfer(self, payment, operation) -> dict: ...


class SubscriptionProvider(Protocol):
    async def subscriber(self, user_id) -> dict: ...
