"""add billing subscriptions bookings and financial operations

Revision ID: 02dc31803a77
Revises: 44752d9c4ff7
Create Date: 2026-09-18 21:26:18.360387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02dc31803a77"
down_revision: Union[str, Sequence[str], None] = "44752d9c4ff7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_provider_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id"),
    )
    op.create_table(
        "billing_ai_usage",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("test_mode", sa.Boolean(), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.CheckConstraint("used >= 0", name="ck_ai_usage_nonnegative"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "day", "test_mode"),
    )
    op.create_table(
        "billing_pricing_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("test_mode", sa.Boolean(), nullable=False),
        sa.Column("tax_bps", sa.Integer(), nullable=False),
        sa.Column("platform_bps", sa.Integer(), nullable=False),
        sa.Column("processor_bps", sa.Integer(), nullable=False),
        sa.Column("processor_fixed_minor", sa.BigInteger(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "tax_bps >= 0 AND platform_bps >= 0 AND processor_bps >= 0 AND tax_bps + platform_bps + processor_bps < 10000 AND processor_fixed_minor >= 0",
            name="ck_pricing_policy",
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_pricing_policies_created_at"),
        "billing_pricing_policies",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "billing_psychologists",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("hourly_net_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("stripe_account_id", sa.String(length=100), nullable=True),
        sa.Column("charges_enabled", sa.Boolean(), nullable=False),
        sa.Column("payouts_enabled", sa.Boolean(), nullable=False),
        sa.CheckConstraint("hourly_net_minor > 0", name="ck_hourly_net_positive"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("stripe_account_id"),
    )
    op.create_table(
        "billing_subscription_purchases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "request_id"),
    )
    op.create_table(
        "billing_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("test_mode", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("will_renew", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "test_mode"),
    )
    op.create_index(
        op.f("ix_billing_subscriptions_user_id"),
        "billing_subscriptions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "billing_bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slot_id", sa.UUID(), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=True),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("psychologist_id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("booked_event_id", sa.UUID(), nullable=True),
        sa.Column("test_mode", sa.Boolean(), nullable=False),
        sa.Column("legacy", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("quote", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hold_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','confirmed','cancelled','expired','completed','missed')",
            name="ck_booking_status",
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["patient_assignments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["booked_event_id"], ["slot_events.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["psychologist_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["slot_id"], ["slots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booked_event_id"),
        sa.UniqueConstraint("patient_id", "request_id"),
    )
    op.create_index(
        op.f("ix_billing_bookings_patient_id"),
        "billing_bookings",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_bookings_psychologist_id"),
        "billing_bookings",
        ["psychologist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_bookings_slot_id"),
        "billing_bookings",
        ["slot_id"],
        unique=False,
    )
    op.create_index(
        "uq_booking_active_slot",
        "billing_bookings",
        ["slot_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending','confirmed')"),
    )
    op.create_table(
        "billing_earnings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("psychologist_id", sa.UUID(), nullable=False),
        sa.Column("test_mode", sa.Boolean(), nullable=False),
        sa.Column("net_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["billing_bookings.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["psychologist_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id"),
    )
    op.create_index(
        op.f("ix_billing_earnings_created_at"),
        "billing_earnings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_earnings_psychologist_id"),
        "billing_earnings",
        ["psychologist_id"],
        unique=False,
    )
    op.create_table(
        "billing_payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("checkout_id", sa.String(length=200), nullable=True),
        sa.Column("checkout_url", sa.String(length=2000), nullable=True),
        sa.Column("destination", sa.String(length=100), nullable=True),
        sa.Column("actual_fee_minor", sa.BigInteger(), nullable=True),
        sa.Column("source_charge", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount_minor > 0", name="ck_payment_positive"),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["billing_bookings.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id"),
        sa.UniqueConstraint("checkout_id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "billing_operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('refund','transfer') AND amount_minor > 0",
            name="ck_money_operation",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["billing_payments.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("payment_id", "kind"),
    )
    op.create_index(
        op.f("ix_billing_operations_retry_at"),
        "billing_operations",
        ["retry_at"],
        unique=False,
    )
    # Existing confirmed reservations remain accessible without a retroactive charge.
    op.execute(
        sa.text("""
        INSERT INTO billing_bookings
          (id, slot_id, patient_id, psychologist_id, request_id, booked_event_id,
           test_mode, legacy, status, quote, hold_until, created_at)
        SELECT gen_random_uuid(), s.id, e.patient_id, s.psychologist_id, gen_random_uuid(), e.id,
               false, true, 'confirmed', '{}'::jsonb, s.start_at, e.created_at
        FROM slots s
        JOIN LATERAL (
          SELECT * FROM slot_events WHERE slot_id = s.id
          ORDER BY created_at DESC, id DESC LIMIT 1
        ) e ON true
        WHERE e.event_type = 'booked' AND e.patient_id IS NOT NULL
    """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_billing_operations_retry_at"), table_name="billing_operations"
    )
    op.drop_table("billing_operations")
    op.drop_table("billing_payments")
    op.drop_index(
        op.f("ix_billing_earnings_psychologist_id"), table_name="billing_earnings"
    )
    op.drop_index(op.f("ix_billing_earnings_created_at"), table_name="billing_earnings")
    op.drop_table("billing_earnings")
    op.drop_index(
        "uq_booking_active_slot",
        table_name="billing_bookings",
        postgresql_where=sa.text("status IN ('pending','confirmed')"),
    )
    op.drop_index(op.f("ix_billing_bookings_slot_id"), table_name="billing_bookings")
    op.drop_index(
        op.f("ix_billing_bookings_psychologist_id"), table_name="billing_bookings"
    )
    op.drop_index(op.f("ix_billing_bookings_patient_id"), table_name="billing_bookings")
    op.drop_table("billing_bookings")
    op.drop_index(
        op.f("ix_billing_subscriptions_user_id"), table_name="billing_subscriptions"
    )
    op.drop_table("billing_subscriptions")
    op.drop_table("billing_subscription_purchases")
    op.drop_table("billing_psychologists")
    op.drop_index(
        op.f("ix_billing_pricing_policies_created_at"),
        table_name="billing_pricing_policies",
    )
    op.drop_table("billing_pricing_policies")
    op.drop_table("billing_ai_usage")
    op.drop_table("billing_provider_events")
    # ### end Alembic commands ###
