"""add call event created at

Revision ID: 11c35ca20c2c
Revises: 8785b6468da8
Create Date: 2026-08-12 16:48:48.702490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c35ca20c2c'
down_revision: Union[str, Sequence[str], None] = '8785b6468da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_call_events_created_at'), 'call_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_events_created_at'), table_name='call_events')
    op.drop_column('call_events', 'created_at')
    # ### end Alembic commands ###
