"""add patient assignments

Revision ID: 20181e61b4fd
Revises: 47b3ade79e43
Create Date: 2026-05-09 20:27:22.819558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20181e61b4fd'
down_revision: Union[str, Sequence[str], None] = '47b3ade79e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('psychologist_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_assignments_patient_id'), 'patient_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_psychologist_id'), 'patient_assignments', ['psychologist_id'], unique=False)
    op.create_table('patient_assignment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('requested', 'accepted', 'rejected', 'finished', 'cancelled', name='patient_assignment_event_type'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['patient_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_assignment_events_assignment_id'), 'patient_assignment_events', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_patient_assignment_events_event_type'), 'patient_assignment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_patient_assignment_events_performed_by_id'), 'patient_assignment_events', ['performed_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_assignment_events_performed_by_id'), table_name='patient_assignment_events')
    op.drop_index(op.f('ix_patient_assignment_events_event_type'), table_name='patient_assignment_events')
    op.drop_index(op.f('ix_patient_assignment_events_assignment_id'), table_name='patient_assignment_events')
    op.drop_table('patient_assignment_events')
    op.drop_index(op.f('ix_patient_assignments_psychologist_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_patient_id'), table_name='patient_assignments')
    op.drop_table('patient_assignments')
    # ### end Alembic commands ###
