"""add calls

Revision ID: 209174a0794e
Revises: ad46a0b2e53f
Create Date: 2026-06-07 01:19:46.651978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209174a0794e'
down_revision: Union[str, Sequence[str], None] = 'ad46a0b2e53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('agora', name='call_provider'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_slot_id'), 'calls', ['slot_id'], unique=True)
    op.create_table('call_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('joined', 'left', 'completed', 'missed', name='call_event_type'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_call_id'), 'call_events', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_events_event_type'), 'call_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_call_events_user_id'), 'call_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_events_user_id'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_event_type'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_call_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_calls_slot_id'), table_name='calls')
    op.drop_table('calls')
    sa.Enum(
        name="call_event_type",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    sa.Enum(
        name="call_provider",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
