"""add slots and slot events

Revision ID: 47b3ade79e43
Revises: d180c40f1327
Create Date: 2026-05-08 20:46:41.647504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b3ade79e43'
down_revision: Union[str, Sequence[str], None] = 'd180c40f1327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('psychologist_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_psychologist_id'), 'slots', ['psychologist_id'], unique=False)
    op.create_index(op.f('ix_slots_start_at'), 'slots', ['start_at'], unique=False)
    op.create_table('slot_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('booked', 'cancelled', 'completed', 'missed', name='slot_event_type'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_events_created_at'), 'slot_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_slot_events_event_type'), 'slot_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_slot_events_patient_id'), 'slot_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_slot_events_slot_id'), 'slot_events', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slot_events_slot_id'), table_name='slot_events')
    op.drop_index(op.f('ix_slot_events_patient_id'), table_name='slot_events')
    op.drop_index(op.f('ix_slot_events_event_type'), table_name='slot_events')
    op.drop_index(op.f('ix_slot_events_created_at'), table_name='slot_events')
    op.drop_table('slot_events')
    op.drop_index(op.f('ix_slots_start_at'), table_name='slots')
    op.drop_index(op.f('ix_slots_psychologist_id'), table_name='slots')
    op.drop_table('slots')
    sa.Enum(
        name="slot_event_type",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
