"""add cached psychologist rating

Revision ID: 64818e65d2aa
Revises: f97726424f21
Create Date: 2026-07-25 22:53:38.627642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64818e65d2aa'
down_revision: Union[str, Sequence[str], None] = 'f97726424f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('users', sa.Column('ratings_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ratings_count')
    op.drop_column('users', 'average_rating')
    # ### end Alembic commands ###
