"""track checkout requests before provider calls

Revision ID: 79d745f6d416
Revises: 02dc31803a77
Create Date: 2026-09-18 21:41:14.872714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d745f6d416'
down_revision: Union[str, Sequence[str], None] = '02dc31803a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_payments', sa.Column('checkout_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_payments', 'checkout_started_at')
    # ### end Alembic commands ###
