"""add ai care plans

Revision ID: 7b8f97bbef71
Revises: 64818e65d2aa
Create Date: 2026-07-30 17:43:19.150293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8f97bbef71'
down_revision: Union[str, Sequence[str], None] = '64818e65d2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_care_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['patient_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_care_plans_assignment_id'), 'ai_care_plans', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_ai_care_plans_created_at'), 'ai_care_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_care_plans_created_by_id'), 'ai_care_plans', ['created_by_id'], unique=False)
    op.create_table('ai_care_plan_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('care_plan_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('instructions_for_ai', sa.Text(), nullable=False),
    sa.Column('patient_recommendations', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['ai_care_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('care_plan_id', 'version', name='uq_ai_care_plan_versions_plan_version')
    )
    op.create_index(op.f('ix_ai_care_plan_versions_care_plan_id'), 'ai_care_plan_versions', ['care_plan_id'], unique=False)
    op.create_index(op.f('ix_ai_care_plan_versions_created_at'), 'ai_care_plan_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_care_plan_versions_created_by_id'), 'ai_care_plan_versions', ['created_by_id'], unique=False)
    op.create_table('ai_care_plan_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('care_plan_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('ACTIVATED', 'PAUSED', 'COMPLETED', name='ai_care_plan_event_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['care_plan_id'], ['ai_care_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['ai_care_plan_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_care_plan_events_actor_id'), 'ai_care_plan_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_ai_care_plan_events_care_plan_id'), 'ai_care_plan_events', ['care_plan_id'], unique=False)
    op.create_index(op.f('ix_ai_care_plan_events_created_at'), 'ai_care_plan_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_care_plan_events_event_type'), 'ai_care_plan_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ai_care_plan_events_version_id'), 'ai_care_plan_events', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_care_plan_events_version_id'), table_name='ai_care_plan_events')
    op.drop_index(op.f('ix_ai_care_plan_events_event_type'), table_name='ai_care_plan_events')
    op.drop_index(op.f('ix_ai_care_plan_events_created_at'), table_name='ai_care_plan_events')
    op.drop_index(op.f('ix_ai_care_plan_events_care_plan_id'), table_name='ai_care_plan_events')
    op.drop_index(op.f('ix_ai_care_plan_events_actor_id'), table_name='ai_care_plan_events')
    op.drop_table('ai_care_plan_events')
    op.execute("DROP TYPE IF EXISTS ai_care_plan_event_type")
    op.drop_index(op.f('ix_ai_care_plan_versions_created_by_id'), table_name='ai_care_plan_versions')
    op.drop_index(op.f('ix_ai_care_plan_versions_created_at'), table_name='ai_care_plan_versions')
    op.drop_index(op.f('ix_ai_care_plan_versions_care_plan_id'), table_name='ai_care_plan_versions')
    op.drop_table('ai_care_plan_versions')
    op.drop_index(op.f('ix_ai_care_plans_created_by_id'), table_name='ai_care_plans')
    op.drop_index(op.f('ix_ai_care_plans_created_at'), table_name='ai_care_plans')
    op.drop_index(op.f('ix_ai_care_plans_assignment_id'), table_name='ai_care_plans')
    op.drop_table('ai_care_plans')
    # ### end Alembic commands ###
