"""add ai message request id

Revision ID: 8785b6468da8
Revises: 7b8f97bbef71
Create Date: 2026-08-12 16:07:36.234310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8785b6468da8'
down_revision: Union[str, Sequence[str], None] = '7b8f97bbef71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('request_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_messages_request_id'), 'ai_messages', ['request_id'], unique=False)
    op.create_unique_constraint('uq_ai_messages_conversation_request_role', 'ai_messages', ['conversation_id', 'request_id', 'role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ai_messages_conversation_request_role', 'ai_messages', type_='unique')
    op.drop_index(op.f('ix_ai_messages_request_id'), table_name='ai_messages')
    op.drop_column('ai_messages', 'request_id')
    # ### end Alembic commands ###
