"""store actual processor fee currency

Revision ID: b07625e126ed
Revises: 79d745f6d416
Create Date: 2026-09-18 21:49:01.220796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07625e126ed'
down_revision: Union[str, Sequence[str], None] = '79d745f6d416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_payments', sa.Column('actual_fee_currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_payments', 'actual_fee_currency')
    # ### end Alembic commands ###
