"""add last_sent_at to pending_registrations

Revision ID: b50ea03fcb59
Revises: 94945055aae3
Create Date: 2026-02-20 14:14:18.317823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b50ea03fcb59'
down_revision: Union[str, Sequence[str], None] = '94945055aae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.add_column('pending_registrations', sa.Column('last_sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_psychologist_profile_user_id'), 'psychologist_profile', ['user_id'], unique=True)
    op.drop_index(op.f('uq_single_owner'), table_name='users', postgresql_where="(role = 'owner'::userrole)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_single_owner'), 'users', ['role'], unique=True, postgresql_where="(role = 'owner'::userrole)")
    op.drop_index(op.f('ix_psychologist_profile_user_id'), table_name='psychologist_profile')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_column('pending_registrations', 'last_sent_at')
    op.create_table('sessions',
    sa.Column('id_sess', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('psychologist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('requested', 'approved', 'rejected', 'canceled', 'finished', name='sessionstatus'), server_default=sa.text("'requested'::sessionstatus"), autoincrement=False, nullable=False),
    sa.Column('jitsi_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], name=op.f('sessions_psychologist_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sess', name=op.f('sessions_pkey'))
    )
    # ### end Alembic commands ###
