"""add patient assignments

Revision ID: bf85b2d1f49f
Revises: b50ea03fcb59
Create Date: 2026-02-20 19:39:46.891398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf85b2d1f49f'
down_revision: Union[str, Sequence[str], None] = 'b50ea03fcb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('psychologist_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='assignmentstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_assignments')
    # ### end Alembic commands ###
