"""add psychologist ratings

Revision ID: d180c40f1327
Revises: c900216ba13a
Create Date: 2026-05-03 21:45:02.103244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd180c40f1327'
down_revision: Union[str, Sequence[str], None] = 'c900216ba13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychologist_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('psychologist_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'psychologist_id', name='uq_psychologist_rating_patient_psychologist')
    )
    op.create_index(op.f('ix_psychologist_ratings_patient_id'), 'psychologist_ratings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_psychologist_ratings_psychologist_id'), 'psychologist_ratings', ['psychologist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psychologist_ratings_psychologist_id'), table_name='psychologist_ratings')
    op.drop_index(op.f('ix_psychologist_ratings_patient_id'), table_name='psychologist_ratings')
    op.drop_table('psychologist_ratings')
    # ### end Alembic commands ###
