"""add ai conversations and messages

Revision ID: f97726424f21
Revises: 209174a0794e
Create Date: 2026-07-10 20:01:50.051120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97726424f21'
down_revision: Union[str, Sequence[str], None] = '209174a0794e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column('mode', sa.Enum('self_help', 'guided', name='ai_conversation_mode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['patient_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_assignment_id'), 'ai_conversations', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_created_at'), 'ai_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_conversations_mode'), 'ai_conversations', ['mode'], unique=False)
    op.create_index(op.f('ix_ai_conversations_patient_id'), 'ai_conversations', ['patient_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='ai_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_created_at'), 'ai_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_role'), 'ai_messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_ai_messages_role"),
        table_name="ai_messages",
    )
    op.drop_index(
        op.f("ix_ai_messages_created_at"),
        table_name="ai_messages",
    )
    op.drop_index(
        op.f("ix_ai_messages_conversation_id"),
        table_name="ai_messages",
    )
    op.drop_table("ai_messages")

    op.drop_index(
        op.f("ix_ai_conversations_patient_id"),
        table_name="ai_conversations",
    )
    op.drop_index(
        op.f("ix_ai_conversations_mode"),
        table_name="ai_conversations",
    )
    op.drop_index(
        op.f("ix_ai_conversations_created_at"),
        table_name="ai_conversations",
    )
    op.drop_index(
        op.f("ix_ai_conversations_assignment_id"),
        table_name="ai_conversations",
    )
    op.drop_table("ai_conversations")

    sa.Enum(name="ai_message_role").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="ai_conversation_mode").drop(
        op.get_bind(),
        checkfirst=True,
    )
